### ISSUE TITLE
PiSchedule 7.1 not properly installing

### ISSUE THREAD

**Issue by Sico93** [neandr/piSchedule#4]
As mentioned in the pilight Forum, i found a Bug in the latest installation Script, which i fixed within only 3 characters :) 

This is, what the bug looked like:

Cleaning up... 
    INFO - System Updating 
    INFO - get piSchedule7 code 
 unzip:  cannot find or open piSchedule.zip, piSchedule.zip.zip or piSchedule.zip.ZIP.
    INFO - reset prefs file 'piSchedule.prefs.json'
 chmod: cannot access ‘/home/pi/piSchedule7/piSchedule.py’: No such file or directory
 chmod: cannot access ‘/home/pi/piSchedule7/piSchedule.sh’: No such file or directory
 chmod: cannot access ‘/home/pi/piSchedule7/piPrefs.py’: No such file or directory
 chmod: cannot access ‘/home/pi/piSchedule7/sunrise_sunset.py’: No such file or directory
 cp: cannot stat ‘/home/pi/piSchedule7/piSchedule.sh’: No such file or directory
 update-rc.d: error: initscript does not exist: /etc/init.d/piSchedule

But lets see what i did:

old & buggy
`
sudo unzip piSchedule.zip -d $HOME7/ -x */piSchedule.prefs.json
`
new & working
`
sudo unzip piSchedule7.1.zip -d $HOME7/ -x */piSchedule.prefs.json
`

I really hope this helps fixing this issue ;)

**Comment by neandr** [comment]
Please move over to piSchedule vers.0.7.3
More details see here https://groups.google.com/forum/#!forum/pischedule7
